### ISSUE TITLE
Auto Refresh not working

### ISSUE THREAD

**Issue by PhillWalker** [aaroncarpenter/fork-board#22]
I believe I noticed this in 0.3.0, but in 0.5.0 the auto refresh time of 5 minutes doesn't seem to happen, the last refresh time missed 3 refresh cycles over 15 minutes, before I had to give in and run it manually

**Comment by aaroncarpenter** [comment]
confirmed fixed in packaged version on MacOs, Windows and Linux.  There was an issue with the way I was calling my refresh function in the interval.
