### ISSUE TITLE
Feature request, sync status of forks

### ISSUE THREAD

**Issue by sparklyballs** [aaroncarpenter/fork-board#43]
As we know some of the forks are less than stable and prone to breakage and the whole blockchain crashing etc.

Is there an api call for the sync status from wherever you get information from on forks.

To be clear I'm not talking about my local sync status but whether the whole blockchain is down and if that information is available could it be integrated into forkboard somehow,

**Comment by aaroncarpenter** [comment]
Any ideas for UI to display this information?  Was initially thinking of something like a stop light.  Red/yellow/green based on the peak age.

**Comment by aaroncarpenter** [comment]
This feature has been added and deployed in v1.0.6 that was released yesterday
